version: "3.9"
services:
  homer:
    image: b4bz/homer:v23.02.2
    container_name: homer
    restart: always
    user: root
    networks:
      - traefik
    volumes:
      - ./docker/homer/assets:/www/assets
      - ./docker/homer/${CONFIG}:/www/assets/config.yml
    environment:
      - INIT_ASSETS=0
    labels:
      - traefik.enable=true
      - traefik.http.routers.homer.rule=Host(`${HOMER_DOMAIN}`)
      - traefik.http.routers.homer.service=homer
      - traefik.http.routers.homer.entryPoints=http

      - traefik.http.routers.homerHttps.rule=Host(`${HOMER_DOMAIN}`)
      - traefik.http.routers.homerHttps.service=homer
      - traefik.http.routers.homerHttps.entryPoints=https
      - traefik.http.routers.homerHttps.tls.certResolver=letsEncrypt

      - traefik.http.services.homer.loadbalancer.server.port=8080


networks:
  traefik:
    external: true
    name: traefik